import type { RiskLimits, RiskState as RiskStateData, TradeRequest } from "../trading/types";
import { evaluateRisk, dayKeyUtc, type TradeContext } from "../trading/risk";

interface RiskPayload {
  cashToken: `0x${string}`;
  trade: { tokenIn: `0x${string}`; tokenOut: `0x${string}`; amountInWei: string; amountOutWei: string; slippageBps: number; reason: string; idempotencyKey?: string };
  context: { currentExposureWei: string; tokenExposureWei: string; openPositions: number; nowMs: number };
  limits: { maxTradeWei: string; maxPortfolioExposureWei: string; maxTokenExposureWei: string; maxOpenPositions: number; maxTradesPerDay: number; cooldownSeconds: number; maxDailyLossWei: string };
}
function defaultState(): RiskStateData { return { killSwitch: false, dayKey: dayKeyUtc(), dailyLossWei: 0n, dailyTrades: 0, lastTradeAtByToken: {} }; }
function requiredBigInt(value: unknown, field: string): bigint { if (typeof value !== "string" && typeof value !== "number" && typeof value !== "bigint") throw new Error(`RiskState ${field} is missing.`); const text = String(value).trim(); if (!text) throw new Error(`RiskState ${field} is empty.`); try { return BigInt(text); } catch { throw new Error(`RiskState ${field} is invalid: ${text.slice(0, 80)}`); } }
function readState(sql: SqlStorage, nowMs: number): RiskStateData { const rows = sql.exec<{ key: string; value: string }>("SELECT key, value FROM risk_meta").toArray(); const values = new Map(rows.map((row: { key: string; value: string }) => [row.key, row.value])); return { killSwitch: values.get("kill_switch") === "1", dayKey: values.get("day_key") ?? dayKeyUtc(new Date(nowMs)), dailyLossWei: requiredBigInt(values.get("daily_loss_wei") ?? "0", "daily_loss_wei"), dailyTrades: Number(values.get("daily_trades") ?? "0"), lastTradeAtByToken: JSON.parse(values.get("last_trade_at_by_token") ?? "{}") as Record<string, number> }; }
function normalizeDay(state: RiskStateData, nowMs: number): RiskStateData { const dayKey = dayKeyUtc(new Date(nowMs)); return state.dayKey === dayKey ? state : { ...defaultState(), dayKey, killSwitch: state.killSwitch }; }
function writeState(sql: SqlStorage, state: RiskStateData): void { sql.exec("INSERT OR REPLACE INTO risk_meta(key, value) VALUES ('kill_switch', ?)", state.killSwitch ? "1" : "0"); sql.exec("INSERT OR REPLACE INTO risk_meta(key, value) VALUES ('day_key', ?)", state.dayKey); sql.exec("INSERT OR REPLACE INTO risk_meta(key, value) VALUES ('daily_loss_wei', ?)", state.dailyLossWei.toString()); sql.exec("INSERT OR REPLACE INTO risk_meta(key, value) VALUES ('daily_trades', ?)", String(state.dailyTrades)); sql.exec("INSERT OR REPLACE INTO risk_meta(key, value) VALUES ('last_trade_at_by_token', ?)", JSON.stringify(state.lastTradeAtByToken)); }
function parseLimits(value: RiskPayload["limits"]): RiskLimits { return { maxTradeWei: requiredBigInt(value.maxTradeWei, "limits.maxTradeWei"), maxPortfolioExposureWei: requiredBigInt(value.maxPortfolioExposureWei, "limits.maxPortfolioExposureWei"), maxTokenExposureWei: requiredBigInt(value.maxTokenExposureWei, "limits.maxTokenExposureWei"), maxOpenPositions: value.maxOpenPositions, maxTradesPerDay: value.maxTradesPerDay, cooldownSeconds: value.cooldownSeconds, maxDailyLossWei: requiredBigInt(value.maxDailyLossWei, "limits.maxDailyLossWei") }; }
function parseTrade(value: RiskPayload["trade"]): TradeRequest { return { tokenIn: value.tokenIn, tokenOut: value.tokenOut, amountInWei: requiredBigInt(value.amountInWei, "trade.amountInWei"), amountOutWei: requiredBigInt(value.amountOutWei, "trade.amountOutWei"), slippageBps: value.slippageBps, reason: value.reason, idempotencyKey: value.idempotencyKey }; }
function parseContext(value: RiskPayload["context"]): TradeContext { return { currentExposureWei: requiredBigInt(value.currentExposureWei, "context.currentExposureWei"), tokenExposureWei: requiredBigInt(value.tokenExposureWei, "context.tokenExposureWei"), openPositions: value.openPositions, nowMs: value.nowMs }; }

export class RiskState {
  private readonly sql: SqlStorage;
  constructor(state: DurableObjectState) { this.sql = state.storage.sql; this.sql.exec("CREATE TABLE IF NOT EXISTS risk_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS risk_idempotency (key TEXT PRIMARY KEY, created_at INTEGER NOT NULL);"); const now = Date.now(); writeState(this.sql, normalizeDay(readState(this.sql, now), now)); }
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url); const nowMs = Date.now(); let state = normalizeDay(readState(this.sql, nowMs), nowMs); writeState(this.sql, state);
    if (url.pathname === "/health") return Response.json({ ok: true, killSwitch: state.killSwitch });
    if (url.pathname === "/state" && request.method === "GET") return Response.json({ killSwitch: state.killSwitch, dayKey: state.dayKey, dailyLossWei: state.dailyLossWei.toString(), dailyTrades: state.dailyTrades, lastTradeAtByToken: state.lastTradeAtByToken });
    if (url.pathname === "/kill-switch" && request.method === "POST") { const body = await request.json() as { enabled: boolean }; state = { ...state, killSwitch: Boolean(body.enabled) }; writeState(this.sql, state); return Response.json({ ok: true, killSwitch: state.killSwitch }); }
    if ((url.pathname === "/check" || url.pathname === "/authorize") && request.method === "POST") { try { const payload = await request.json() as RiskPayload; const trade = parseTrade(payload.trade); const limits = parseLimits(payload.limits); const context = parseContext(payload.context); const cashToken = payload.cashToken; if (!cashToken) throw new Error("RiskState cashToken is missing."); const check = evaluateRisk(trade, limits, state, context, cashToken); if (!check.ok) return Response.json({ ok: false, reason: check.reason }, { status: 409 }); if (url.pathname === "/check") return Response.json({ ok: true, dryRun: true }); if (trade.idempotencyKey) { if (this.sql.exec("SELECT key FROM risk_idempotency WHERE key = ?", trade.idempotencyKey).one()) return Response.json({ ok: false, reason: "Duplicate idempotency key." }, { status: 409 }); this.sql.exec("INSERT INTO risk_idempotency(key, created_at) VALUES (?, ?)", trade.idempotencyKey, nowMs); } const isBuy = trade.tokenIn.toLowerCase() === cashToken.toLowerCase(); const token = (isBuy ? trade.tokenOut : trade.tokenIn).toLowerCase(); state = { ...state, dailyTrades: state.dailyTrades + 1, lastTradeAtByToken: { ...state.lastTradeAtByToken, [token]: nowMs } }; writeState(this.sql, state); return Response.json({ ok: true, state: { dailyTrades: state.dailyTrades } }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Risk authorization failed." }, { status: 400 }); } }
    if (url.pathname === "/settle" && request.method === "POST") { const body = await request.json() as { realizedPnlDeltaWei: string }; const delta = requiredBigInt(body.realizedPnlDeltaWei, "settle.realizedPnlDeltaWei"); state = { ...state, dailyLossWei: delta < 0n ? state.dailyLossWei + (-delta) : state.dailyLossWei }; writeState(this.sql, state); return Response.json({ ok: true, dailyLossWei: state.dailyLossWei.toString() }); }
    return Response.json({ ok: false, error: "Not found" }, { status: 404 });
  }
}
